dist: focal

language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

matrix:
    include:
        - os: linux

cache: pip

before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install requests

install:
  - pip install --upgrade pip
  - pip install .
  - pip install pytest pytest-cov codecov

script:
  - pytest eleanor/tests/* --cov=eleanor/

after_success:
  - codecov
